# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: croc.space
# email: crok91@gmail.com
# description: The life and times of a modern-age crocodile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://croc.space/" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: croc.space
# twitter_username: jekyllrb
# github_username:  lzrmihnea

layout: default
comments: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# File: _config.yml
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

# Customization
permalink: /a/:title

disqus:
  shortname: lzrmihnea-github-io
